### PR TITLE
build(all): add formatter, linter, precommit hooks, github action check

### LINKED ISSUE #71: [Super AI] Init Project Structure
We should have the following features in our code base
- [ ] Pytest
- [ ] CI, Formatter, Linter

### PR DESCRIPTION
**Pull request by new5558**
This PR adds tons of static code checkers:
- MyPy for type checking
- Flake8 for styles guide
- Black for code formatting

Checker will run on the following conditions:
- automatically format/lint if you are using VS Code
- committing files in Git
- When opening PR

To test this PR for commit hooks do:
- checkout to `new/formater` branch
- Run `pip install -r requirements.txt` and `pre-commit install`
- Edit/Create any python file and stage changes
- Try to commit. At this point **we should have all checkers running against your staged files**

Close #71

### CODE REVIEW

**Comment by ArthurMinovsky** [comment]
ok for test

**Review by boat1603 — APPROVED** [review]
LGTM for this PR. But I followed [README.md](https://github.com/OpenThaiGPT/openthaigpt-pretraining/blob/8b166149433d21118647d0c3508d0dbefa7a206f/README.md) instruction. I think `pip install -e ./tests/<module_name>` that we added in the PR #68 should be deleted. We should fix it in the next PR.

**Review by ArthurMinovsky — APPROVED** [review]
ok

**Review by kriangkraitan — APPROVED** [review]

**Review by MoosaTae — APPROVED** [review]

**Review by MoosaTae — APPROVED** [review]

**Review by boss-chanon — APPROVED** [review]

**Review by pitikorn32 — APPROVED** [review]

**Review by Pattptr — APPROVED** [review]

**Review by nuchhub — APPROVED** [review]
test approve

**Pull request merged**
